/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEngineerIndexRouteImport } from './routes/_authenticated/engineer/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAccountantIndexRouteImport } from './routes/_authenticated/accountant/index'
import { Route as AuthenticatedEngineerProjectIdRouteImport } from './routes/_authenticated/engineer/$projectId'
import { Route as AuthenticatedClientNewRouteImport } from './routes/_authenticated/client/new'
import { Route as AuthenticatedClientProjectIdRouteImport } from './routes/_authenticated/client/$projectId'
import { Route as AuthenticatedEngineerProjectIdWorksheetRouteImport } from './routes/_authenticated/engineer/$projectId.worksheet'
import { Route as AuthenticatedEngineerProjectIdQuotationRouteImport } from './routes/_authenticated/engineer/$projectId.quotation'
import { Route as AuthenticatedEngineerProjectIdMessagesRouteImport } from './routes/_authenticated/engineer/$projectId.messages'
import { Route as AuthenticatedEngineerProjectIdInspectionRouteImport } from './routes/_authenticated/engineer/$projectId.inspection'
import { Route as AuthenticatedEngineerProjectIdCompareRouteImport } from './routes/_authenticated/engineer/$projectId.compare'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineerIndexRoute =
  AuthenticatedEngineerIndexRouteImport.update({
    id: '/engineer/',
    path: '/engineer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountantIndexRoute =
  AuthenticatedAccountantIndexRouteImport.update({
    id: '/accountant/',
    path: '/accountant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngineerProjectIdRoute =
  AuthenticatedEngineerProjectIdRouteImport.update({
    id: '/engineer/$projectId',
    path: '/engineer/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNewRoute = AuthenticatedClientNewRouteImport.update({
  id: '/client/new',
  path: '/client/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientProjectIdRoute =
  AuthenticatedClientProjectIdRouteImport.update({
    id: '/client/$projectId',
    path: '/client/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngineerProjectIdWorksheetRoute =
  AuthenticatedEngineerProjectIdWorksheetRouteImport.update({
    id: '/worksheet',
    path: '/worksheet',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdQuotationRoute =
  AuthenticatedEngineerProjectIdQuotationRouteImport.update({
    id: '/quotation',
    path: '/quotation',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdMessagesRoute =
  AuthenticatedEngineerProjectIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdInspectionRoute =
  AuthenticatedEngineerProjectIdInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdCompareRoute =
  AuthenticatedEngineerProjectIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/accountant/': typeof AuthenticatedAccountantIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/accountant': typeof AuthenticatedAccountantIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/engineer': typeof AuthenticatedEngineerIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/_authenticated/client/new': typeof AuthenticatedClientNewRoute
  '/_authenticated/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/_authenticated/accountant/': typeof AuthenticatedAccountantIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/_authenticated/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/_authenticated/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/_authenticated/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/_authenticated/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/_authenticated/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/accountant/'
    | '/admin/'
    | '/client/'
    | '/engineer/'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/accountant'
    | '/admin'
    | '/client'
    | '/engineer'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/client/$projectId'
    | '/_authenticated/client/new'
    | '/_authenticated/engineer/$projectId'
    | '/_authenticated/accountant/'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/engineer/'
    | '/_authenticated/engineer/$projectId/compare'
    | '/_authenticated/engineer/$projectId/inspection'
    | '/_authenticated/engineer/$projectId/messages'
    | '/_authenticated/engineer/$projectId/quotation'
    | '/_authenticated/engineer/$projectId/worksheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer/': {
      id: '/_authenticated/engineer/'
      path: '/engineer'
      fullPath: '/engineer/'
      preLoaderRoute: typeof AuthenticatedEngineerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accountant/': {
      id: '/_authenticated/accountant/'
      path: '/accountant'
      fullPath: '/accountant/'
      preLoaderRoute: typeof AuthenticatedAccountantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer/$projectId': {
      id: '/_authenticated/engineer/$projectId'
      path: '/engineer/$projectId'
      fullPath: '/engineer/$projectId'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/new': {
      id: '/_authenticated/client/new'
      path: '/client/new'
      fullPath: '/client/new'
      preLoaderRoute: typeof AuthenticatedClientNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/$projectId': {
      id: '/_authenticated/client/$projectId'
      path: '/client/$projectId'
      fullPath: '/client/$projectId'
      preLoaderRoute: typeof AuthenticatedClientProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer/$projectId/worksheet': {
      id: '/_authenticated/engineer/$projectId/worksheet'
      path: '/worksheet'
      fullPath: '/engineer/$projectId/worksheet'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdWorksheetRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/quotation': {
      id: '/_authenticated/engineer/$projectId/quotation'
      path: '/quotation'
      fullPath: '/engineer/$projectId/quotation'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdQuotationRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/messages': {
      id: '/_authenticated/engineer/$projectId/messages'
      path: '/messages'
      fullPath: '/engineer/$projectId/messages'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdMessagesRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/inspection': {
      id: '/_authenticated/engineer/$projectId/inspection'
      path: '/inspection'
      fullPath: '/engineer/$projectId/inspection'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdInspectionRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/compare': {
      id: '/_authenticated/engineer/$projectId/compare'
      path: '/compare'
      fullPath: '/engineer/$projectId/compare'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdCompareRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
  }
}

interface AuthenticatedEngineerProjectIdRouteChildren {
  AuthenticatedEngineerProjectIdCompareRoute: typeof AuthenticatedEngineerProjectIdCompareRoute
  AuthenticatedEngineerProjectIdInspectionRoute: typeof AuthenticatedEngineerProjectIdInspectionRoute
  AuthenticatedEngineerProjectIdMessagesRoute: typeof AuthenticatedEngineerProjectIdMessagesRoute
  AuthenticatedEngineerProjectIdQuotationRoute: typeof AuthenticatedEngineerProjectIdQuotationRoute
  AuthenticatedEngineerProjectIdWorksheetRoute: typeof AuthenticatedEngineerProjectIdWorksheetRoute
}

const AuthenticatedEngineerProjectIdRouteChildren: AuthenticatedEngineerProjectIdRouteChildren =
  {
    AuthenticatedEngineerProjectIdCompareRoute:
      AuthenticatedEngineerProjectIdCompareRoute,
    AuthenticatedEngineerProjectIdInspectionRoute:
      AuthenticatedEngineerProjectIdInspectionRoute,
    AuthenticatedEngineerProjectIdMessagesRoute:
      AuthenticatedEngineerProjectIdMessagesRoute,
    AuthenticatedEngineerProjectIdQuotationRoute:
      AuthenticatedEngineerProjectIdQuotationRoute,
    AuthenticatedEngineerProjectIdWorksheetRoute:
      AuthenticatedEngineerProjectIdWorksheetRoute,
  }

const AuthenticatedEngineerProjectIdRouteWithChildren =
  AuthenticatedEngineerProjectIdRoute._addFileChildren(
    AuthenticatedEngineerProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientProjectIdRoute: typeof AuthenticatedClientProjectIdRoute
  AuthenticatedClientNewRoute: typeof AuthenticatedClientNewRoute
  AuthenticatedEngineerProjectIdRoute: typeof AuthenticatedEngineerProjectIdRouteWithChildren
  AuthenticatedAccountantIndexRoute: typeof AuthenticatedAccountantIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedEngineerIndexRoute: typeof AuthenticatedEngineerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientProjectIdRoute: AuthenticatedClientProjectIdRoute,
  AuthenticatedClientNewRoute: AuthenticatedClientNewRoute,
  AuthenticatedEngineerProjectIdRoute:
    AuthenticatedEngineerProjectIdRouteWithChildren,
  AuthenticatedAccountantIndexRoute: AuthenticatedAccountantIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedEngineerIndexRoute: AuthenticatedEngineerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
